### ISSUE TITLE
How can I make the Pro Plan accept more file size, pages and uploads?

### ISSUE THREAD

**Issue by JasonMKY** [joschan21/quill#13]
How can I edit the Pro Plan to accept bigger file size, more pages and uploads?
![image](https://github.com/joschan21/quill/assets/104327713/60be1793-6031-47d2-98b6-ad908b4f2846)

**Comment by anand-mukul** [comment]
@JasonMKY Here, How you can do it,

Update the File Size in src\app\api\uploadthing\core.ts 
Update the Number of pages in src\config\stripe.ts

Note: Also update it relative files 👍 
You can also check this for other issues: https://github.com/anand-mukul/PDFNinja

**Comment by joschan21** [comment]
We did this during the end of the video, thanks anand for the summary!

**Comment by JasonMKY** [comment]
> @JasonMKY Here, How you can do it,
> 
> Update the File Size in src\app\api\uploadthing\core.ts Update the Number of pages in src\config\stripe.ts
> 
> Note: Also update it relative files 👍 You can also check this for other issues: https://github.com/anand-mukul/PDFNinja



> We did this during the end of the video, thanks anand for the summary!

Thanks, also where is the video? I don't see it in the readme.

**Comment by joschan21** [comment]
Pretty much near the end during the final tweaks

**Comment by JasonMKY** [comment]
> Pretty much near the end during the final tweaks

I am asking where the video is? I do not see any video anywhere, I found this from Github. Give me the link to the tutorial video, thanks.
