### ISSUE TITLE
uploading on vercel

### ISSUE THREAD

**Issue by ejemi1989** [joschan21/quill#15]
I encountered the problem of "ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up to date with package.json"

**Comment by anand-mukul** [comment]
Follow these steps : @ejemi1989 

1. **Update `pnpm`:** 
      Make sure you have the latest `pnpm` version installed globally.

   ```bash
   pnpm install -g pnpm@latest
   ```

2. **Delete Files:** 
      Remove the existing `pnpm-lock.yaml` file and the `node_modules` folder.

   ```bash
   rm pnpm-lock.yaml
   rm -rf node_modules
   ```

3. **Install Packages Again:**
   
   ```bash
   pnpm install
   ```

   This will generate a new lockfile and install packages.

For other code related issues you can [check Here](https://github.com/anand-mukul/PDFNinja) 👍

**Comment by joschan21** [comment]
Thanks for helping! :)
