### ISSUE TITLE
Too many pages in PDF

### ISSUE THREAD

**Issue by Manice18** [joschan21/quill#22]
I checked everything, but it still keeps showing "Too many pages in PDF"

I also cloned it and put my .env file but still same issues.
Also tried all the possible solutions in #2  but it's stiil the same error.

Any fix @joschan21 ?
Is it because pinecone got updated ?

**Comment by JasonMKY** [comment]
> I checked everything, but it still keeps showing "Too many pages in PDF"
> 
> I also cloned it and put my .env file but still same issues. Also tried all the possible solutions in #2 but it's stiil the same error.
> 
> Any fix @joschan21 ? Is it because pinecone got updated ?

I see that this is marked as solved, I have this issue when uploading 1 page PDF. What did you do to fix it?

**Comment by Manice18** [comment]
@JasonMKY check discord, i posted the solution with the title: "Solution to "Too many pages in PDF"

**Comment by Sujan1714** [comment]
> @JasonMKY check discord, i posted the solution with the title: "Solution to "Too many pages in PDF"

Discord link
