### ISSUE TITLE
Error [InsufficientQuotaError]: You exceeded your current quota, please check your plan and billing details.

### ISSUE THREAD

**Issue by hempun10** [joschan21/quill#35]
Hello folks,

After the update of pinecone has anyone face issue of `Error [InsufficientQuotaError]: You exceeded your current quota, please check your plan and billing details.
    at Object.defaultFailedAttemptHandler [as onFailedAttempt] (webpack-internal:///(rsc)/./node_modules/.pnpm/langchain@0.0.176_@pinecone-database+pinecone@0.1.6_pdf-parse@1.1.1/node_modules/langchain/dist/util/async_caller.js:37:21)
    at RetryOperation.eval [as _fn] (webpack-internal:///(rsc)/./node_modules/.pnpm/p-retry@4.6.2/node_modules/p-retry/index.js:55:39)`  

I had seen a lot of deployed app are also throwing error on uploading pdf. 

Examle: https://pdfninja.vercel.app/
This app is also showing FAILED comp on ChatWrapper. @joschan21 @biplobsd 

<img width="617" alt="image" src="https://github.com/joschan21/quill/assets/106392313/b940735a-9ce1-4ed2-87ee-1a1f42906cb8">

**Comment by Sahil-pvt** [comment]
Same problem, have you got any solution??

**Comment by Roromus** [comment]
Same problem, when someone find the solution tell us pls.

**Comment by stabildev** [comment]
This issue comes from OpenAI, not from Pinecone. You have to go to your OpenAI account > Billing and buy credits

**Comment by Sahil-pvt** [comment]
> This issue comes from OpenAI, not from Pinecone. You have to go to your OpenAI account > Billing and buy credits

Thanks it worked for me, my credit was expired. I changed the OpenAI account and now it is working.

**Comment by baghelkunalpal** [comment]
in mine its not working i have $5 still its same issue im not able to chat with pdf

**Comment by baghelkunalpal** [comment]
@hempun10 have you resolve the issue
