### ISSUE TITLE
kindeAuth/route.ts Error when deploying to Vercel 

### ISSUE THREAD

**Issue by ck18sss** [joschan21/quill#54]
I am getting an error in kindeAuth/route.ts when I deploy to Vercel. 

<img width="422" alt="image" src="https://github.com/joschan21/quill/assets/141846543/db0bb8e0-7a96-4467-9df4-60736ffef86c">

<html>
<body>

Failed to compile.
--
13:43:41.548 |  
13:43:41.549 | src/app/api/auth/[kindeAuth]/route.ts
13:43:41.549 | Type error: Route "src/app/api/auth/[kindeAuth]/route.ts" has an invalid export:
13:43:41.549 | "Promise<(req: any, res: any) => any>" is not a valid GET return type:
13:43:41.549 | Expected "void \| Response \| Promise<void \| Response>", got "Promise<(req: any, res: any) => any>".
13:43:41.550 | Expected "Promise<void \| Response>", got "Promise<(req: any, res: any) => any>".
13:43:41.550 | Expected "void \| Response", got "(req: any, res: any) => any".
13:43:41.550 |  
13:43:41.702 | Error: Command "npm run build" exited with 1

</body>
</html>

It works fine in the local environment. Here is my repository: https://github.com/ck18sss/InquireAI_v2

This is the code in kindeAuth:

```
import { handleAuth } from '@kinde-oss/kinde-auth-nextjs/server'
import { NextRequest } from 'next/server'

export async function GET(
  request: NextRequest,
  { params }: any
) {
  const endpoint = params.kindeAuth
  return handleAuth(request, endpoint)
}
```

**Comment by ck18sss** [comment]
Getting more type errors unfortunately, when trying to deploy. 

<img width="308" alt="image" src="https://github.com/joschan21/quill/assets/141846543/17184524-482e-4efc-ac95-a5987dfdfbc9">

**Comment by purnellbp** [comment]
Kinde changed some things. I just used their example repo and made a few changes. [kinde-nextjs-app-router-starter-kit](https://github.com/kinde-starter-kits/kinde-nextjs-app-router-starter-kit)

Things to take notice:
- getUser has changed. So for example 
``` const user = await getUser();```
- Auth route changed too. 
```
import { handleAuth } from "@kinde-oss/kinde-auth-nextjs/server";

export const GET = handleAuth();

```
