### ISSUE TITLE
Uploadthing - unable to get presigned urls

### ISSUE THREAD

**Issue by LukeWebster-Khan** [joschan21/quill#57]
https://github.com/joschan21/quill/assets/85649986/db6da89c-9eb7-41a6-97b8-02b2f94d38d4

My pdf uploader route is returning 500. I cannot find any information on the issue with `presigned urls` in the uploadthing docs

Does anyone know how to resolve?

My current code can be found here: https://github.com/LukeWebster-Khan/docqueryhub

**Comment by anand-mukul** [comment]
@LukeWebster-Khan   Here is how you can do it:

1. Don't update the package.json file.

Demo : [PDF Ninja Demo](https://pdfninja-new.vercel.app)

Note: Check out my repository for reference 👍

You can also refer to this link for other issues: [PDF Ninja Repository](https://github.com/anand-mukul/PDFNinja)

**Comment by LukeWebster-Khan** [comment]
After re-installing packages with yarn instead of PNPM, the issue has been resolved. I'm unsure of the initial reason for the error...
