### ISSUE TITLE
 Build failed because of webpack errors

### ISSUE THREAD

**Issue by ODOGRU77** [joschan21/quill#9]
By following the video, I have successfully deployed the "inital commit" version of the app, then Josh has made some changes inside the code and I have followed, but as you can see while deploying the"stripe stuff" version, I get the error " Build failed because of webpack errors", I leave the screenshot that I get in VSCode.  I have checked the spelling errors and all other possible mistakes that I could have made.

![image](https://github.com/joschan21/quill/assets/100802815/1c7206f9-0c16-4fe5-9efc-288a1ce8fdcf)

**Comment by anand-mukul** [comment]
> By following the video, I have successfully deployed the "inital commit" version of the app, then Josh has made some changes inside the code and I have followed, but as you can see while deploying the"stripe stuff" version, I get the error " Build failed because of webpack errors", I leave the screenshot that I get in VSCode. I have checked the spelling errors and all other possible mistakes that I could have made.
> 
> ![image](https://user-images.githubusercontent.com/100802815/273467139-1c7206f9-0c16-4fe5-9efc-288a1ce8fdcf.png)

I can help you with this, But need more details
Can you please share PdfRenderer file?

**Comment by ODOGRU77** [comment]
Josh has sent the next.config.js file and it solved the problem.
