### ISSUE TITLE
Property 'id' does not exist on type 'KindeUser | null'.ts(2339) on src\app\api\message\route.ts

### ISSUE THREAD

**Issue by Sujan1714** [joschan21/quill#93]
src\app\api\message\route.ts

![image](https://github.com/joschan21/quill/assets/106664771/f2e59e7c-e820-44ae-bc01-bf5e196a7c6c)

**Comment by aradhyas8** [comment]
Use this :

```
const { getUser } =  getKindeServerSession()
 const user = await getUser()

 const userId = user?.id

 if(!userId) return new Response('Unauthorized', {status: 401})

```

**Comment by Sujan1714** [comment]
> Use this :
> 
> ```
> const { getUser } =  getKindeServerSession()
>  const user = await getUser()
> 
>  const userId = user?.id
> 
>  if(!userId) return new Response('Unauthorized', {status: 401})
> ```

Thank you it's working

**Comment by Sujan1714** [comment]
Can you help me to solve this error 

![IMG_20240410_195919764_HDR](https://github.com/joschan21/quill/assets/106664771/d56076ed-f36a-4b3f-8b91-3bb594a80c59)

**Comment by aradhyas8** [comment]
Not related to the issue opened. Post separately for other issues.

**Comment by Sujan1714** [comment]
.
